import { Occupant } from '../screens/OverworldScreen/interfaces/Occupants/Occupant';
import {
	flamingDesertMerchant,
	starterTownMerchant,
} from './uniqueOccupants/merchants';
import {
	OakAfterSelection,
	OakBeforeSelection,
	OakDuringSelection,
	nightPokemonFan,
	oaksAssistant,
	oaksAssistant2,
	pikachuFan,
	youngsterJimmyBlocker,
} from './uniqueOccupants/npcs';
import {
	pokeCenterNurse,
	pokeCenterNurseQuest,
} from './uniqueOccupants/nurses';
import {
	berryPatchItem1,
	flamingDesertItem1,
	flamingDesertItem2,
	flamingDesertItem3,
	flamingDesertItem4,
	starterTownItem1,
	starterTownItem2,
} from './uniqueOccupants/overworldItems';
import {
	aceTrainerMelanie,
	brock,
	brocksMinion,
	brocksMinion2,
	bugcatcherBarry,
	bugcatcherCisco,
	bugcatcherNash,
	bugcatcherRalph,
	cowgirlAlex,
	farmerPike,
	hikerBennet,
	pyromaniacJavi,
	youngsterJimmy,
} from './uniqueOccupants/trainers';

export const uniqueOccupantIds = [
	'oak-before-selection',
	'oak-during-selection',
	'oak-after-selection',
	'starter-town-nurse-quest',
	'starter-town-merchant',
	'starter-town-nurse',
	'ballMachine',
	'starter-town-item-1',
	'starter-town-item-2',
	'youngster-jimmy',
	'brock',
	'brocks-minion',
	'brocks-minion2',
	'youngster-jimmy-blocker',
	'oaks-assistant',
	'oaks-assistant2',
	'pikachu-fan',
	'bugCatcher-barry',
	'bugCatcher-nash',
	'bugCatcher-ralph',
	'bugCatcher-cisco',
	'berry-patch-item-1',
	'ace-trainer-melanie',
	'hiker-bennet',
	'farmer-pike',
	'cowgirl-alex',
	'pyromaniac-javi',
	'flaming-desert-merchant',
	'flaming-desert-item-1',
	'flaming-desert-item-2',
	'flaming-desert-item-3',
	'flaming-desert-item-4',
	'night-pokemon-fan',
] as const;
//every occupant that can be handled should be unique
export type UniqueOccupantId = (typeof uniqueOccupantIds)[number];

export const UniqueOccupantRecord: Record<UniqueOccupantId, Occupant> = {
	'youngster-jimmy': youngsterJimmy,
	'youngster-jimmy-blocker': youngsterJimmyBlocker,
	brock,
	'brocks-minion': brocksMinion,
	'brocks-minion2': brocksMinion2,
	'starter-town-item-1': starterTownItem1,
	'starter-town-item-2': starterTownItem2,
	'oak-before-selection': OakBeforeSelection,
	'oak-during-selection': OakDuringSelection,
	'oak-after-selection': OakAfterSelection,
	'starter-town-nurse-quest': pokeCenterNurseQuest,
	'starter-town-merchant': starterTownMerchant,
	'starter-town-nurse': pokeCenterNurse,
	ballMachine: {
		id: 'ballMachine',
		type: 'LARGE_OBSTACLE',
		position: {
			y: 2,
			x: 3,
			mapId: 'oaks-lab',
			orientation: 0,
		},
		sprite: 'pokeballMachine',
		height: 3,
		width: 2,
		clearanceBehind: 1,
		onClick: {
			type: 'ROUTE',
			to: '/starterSelection',
			questCondition: {
				id: 'pickStarter',
				status: 'active',
			},
			conditionalMessages: [
				{
					id: 'pickStarter',
					status: 'inactive',
					message: ['You should speak to the Professor first.'],
				},
				{
					id: 'pickStarter',
					status: 'completed',
					message: ['You can only pick one Pokemon.'],
				},
			],
		},
	},
	'oaks-assistant': oaksAssistant,
	'oaks-assistant2': oaksAssistant2,
	'pikachu-fan': pikachuFan,
	'bugCatcher-barry': bugcatcherBarry,
	'bugCatcher-cisco': bugcatcherCisco,
	'bugCatcher-nash': bugcatcherNash,
	'bugCatcher-ralph': bugcatcherRalph,
	'berry-patch-item-1': berryPatchItem1,
	'pyromaniac-javi': pyromaniacJavi,
	'ace-trainer-melanie': aceTrainerMelanie,
	'cowgirl-alex': cowgirlAlex,
	'farmer-pike': farmerPike,
	'hiker-bennet': hikerBennet,
	'flaming-desert-merchant': flamingDesertMerchant,
	'flaming-desert-item-1': flamingDesertItem1,
	'flaming-desert-item-2': flamingDesertItem2,
	'flaming-desert-item-3': flamingDesertItem3,
	'flaming-desert-item-4': flamingDesertItem4,
	'night-pokemon-fan': nightPokemonFan,
};
