import { MapEncounter, MapState } from '../../store/slices/MapSlice';
import { UniqueOccupantRecord } from '../UniqueOccupantRecord';
import {
	flamingDesertToStarterTown,
	flamingDesertToStarterTown2,
} from './portals';

export const flamingDesertEncounters: MapEncounter[] = [
	{ xp: 400, dexId: 218, rarity: 3 },
	{ xp: 400, dexId: 328, rarity: 3 },
	{ xp: 400, dexId: 58, rarity: 2 },
	{ xp: 400, dexId: 231, rarity: 3 },
	{ xp: 400, dexId: 104, rarity: 3 },
	{ xp: 400, dexId: 529, rarity: 3 },
	{ xp: 400, dexId: 322, rarity: 3 },
	{ xp: 800, dexId: 115, rarity: 1 },
	{ xp: 600, dexId: 554, rarity: 1 },
	{ xp: 600, dexId: 443, rarity: 1, timeOfDay: 'MORNING' },
	{ xp: 400, dexId: 551, rarity: 2, timeOfDay: 'EVENING' },
	{ xp: 600, dexId: 228, rarity: 2, timeOfDay: 'NIGHT' },
];

const mapId = 'flaming-desert';
export const flamingDesert: MapState = {
	environment: 'desert',
	mapId,
	height: 11,
	width: 32,
	baseTile: { id: 'beach', pattern: 'uniform' },
	encounterOnEveryField: true,

	interactives: Object.fromEntries(
		Object.entries(UniqueOccupantRecord).filter(
			(entry) => entry[1].position.mapId === mapId
		)
	),
	decorators: [flamingDesertToStarterTown, flamingDesertToStarterTown2],
	obstacles: [
		{
			type: 'OBSTACLE',
			id: 'starterTownSign',
			sprite: 'smallSign',
			dialogue: ['<- Starter Town'],
			position: {
				x: 1,
				y: 4,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar1',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 4,
				y: 1,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar2',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 4,
				y: 10,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar3',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 1,
				y: 1,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar4',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 3,
				y: 2,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'OBSTACLE',
			id: 'stone',
			sprite: 'ancientStone',
			position: {
				x: 28,
				y: 3,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar1',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 0,
				y: 7,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar2',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 7,
				y: 8,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar3',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 0,
				y: 4,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar4',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 0,
				y: 2,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'OBSTACLE',
			id: 'stone',
			sprite: 'ancientStone',
			position: {
				x: 5,
				y: 9,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar1',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 6,
				y: 5,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar2',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 12,
				y: 6,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar3',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 5,
				y: 1,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar4',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 12,
				y: 1,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'OBSTACLE',
			id: 'stone',
			sprite: 'ancientStone',
			position: {
				x: 14,
				y: 5,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar2',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 10,
				y: 8,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar3',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 2,
				y: 7,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar4',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 8,
				y: 5,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'OBSTACLE',
			id: 'stone',
			sprite: 'ancientStone',
			position: {
				x: 12,
				y: 8,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar1',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 9,
				y: 9,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar2',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 23,
				y: 2,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar3',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 20,
				y: 9,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar4',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 19,
				y: 5,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'OBSTACLE',
			id: 'stone',
			sprite: 'ancientStone',
			position: {
				x: 4,
				y: 4,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar1',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 26,
				y: 8,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar2',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 17,
				y: 5,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar3',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 15,
				y: 2,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'LARGE_OBSTACLE',
			id: 'pillar',
			sprite: 'ancientPillar4',
			height: 2,
			width: 1,
			clearanceBehind: 1,
			position: {
				x: 24,
				y: 5,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
		{
			type: 'OBSTACLE',
			id: 'stone',
			sprite: 'ancientStone',
			position: {
				x: 17,
				y: 8,
				orientation: 0,
				mapId: 'flaming-desert',
				forwardFoot: 0,
			},
		},
	],
	encounters: flamingDesertEncounters,
};
