export enum ItemName {
	'master-ball' = 'master-ball',
	'poke-ball' = 'poke-ball',
	'ultra-ball' = 'ultra-ball',
	'great-ball' = 'great-ball',
	'safari-ball' = 'safari-ball',
	'net-ball' = 'net-ball',
	'dive-ball' = 'dive-ball',
	'nest-ball' = 'nest-ball',
	'timer-ball' = 'timer-ball',
	'luxury-ball' = 'luxury-ball',
	'repeat-ball' = 'repeat-ball',
	'dusk-ball' = 'dusk-ball',
	'heal-ball' = 'heal-ball',
	'quick-ball' = 'quick-ball',
	'cherish-ball' = 'cherish-ball',
	potion = 'potion',
	repel = 'repel',
}
